### PR TITLE
RECOMP-418: Fix generating data on Windows

### PR DESCRIPTION
**Pull request by TGiles**

### CODE REVIEW

**Comment by TGiles** [comment]
I'm not the greatest at Python, so there may be a better way to do all this, but this works for my Windows machine...so grain of salt and all that.

**Comment by hannajones** [comment]
I'm not sure why, but this breaks things for me on mac. I get a bunch of warnings that `rg: ripgrep requires at least one pattern to execute a search`, although the output also make it look like queries got executed 🤔 

Screenshot 2024-04-10 at 2 47 24 PM

and `data` in `progress.json` and `snapshot.json` is just an empty object:

Screenshot 2024-04-10 at 2 47 15 PM
Screenshot 2024-04-10 at 2 47 04 PM

**Comment by TGiles** [comment]
Thanks for taking a look @hannajones , I'll dig into it more on my mac and see if I can get something that works across platforms

**Comment by TGiles** [comment]
Looks like if we drop the `shell=True` part, then the command runs as expected on Mac. I think the command sent to `subprocess.run` ends up being `"rg" "{query}" "{mozilla_central_dir}" "--count" instead of being `"rg {query} {mozilla_central_dir} --count"

**Comment by hannajones** [comment]
Running the latest changes on Mac and there still seem to be some discrepancies in the data getting generated. This first file is what I get for `progress.json` from running the data generation command on the main branch:

[progress.json](https://github.com/FirefoxUX/recomp-metrics/files/14981087/progress.json)

And this is what I'm getting when I'm on this branch locally:

[progress-branch.json](https://github.com/FirefoxUX/recomp-metrics/files/14981088/progress-branch.json)

Most notable differences are:

- it's still generating empty data for the date "2024-04-10" for some reason?

```json
{
  "data": {},
  "date": "2024-04-10",
  "revision": "e21f6f5c4e955cf97af9959683355b990773d9d5"
}
```

- the numbers for "2024-04-03" seem weirdly inflated in some cases

To be honest I'm not really sure _why_ any of that is happening - maybe @mstriemer can shed some light?

**Review by hannajones — APPROVED** [review]
:shipit:

**Pull request merged**
